version: '3.3'

services:
  parser:
    build:
      context: .
      dockerfile: ./ParserSql/Dockerfile
    container_name: parser_container
    volumes:
      - ./BotSqlJava/ProcurementsDB:/ParserSql/ProcurementsDB/
    networks:
      supernetwork:
        ipv4_address: 172.20.0.5

  bot:
    build:
      context: .
      dockerfile: ./BotSqlJava/Dockerfile
    container_name: bot_container
    volumes:
      - ./BotSqlJava/ProcurementsDB:/BotSqlJava/ProcurementsDB
    networks:
      supernetwork:
        ipv4_address: 172.20.0.6
    depends_on:
      - parser


networks:
  supernetwork:
    ipam:
      config:
        - subnet: 172.20.0.0/24

volumes:
  parser:
  bot: