version: '3.3'

services:
  parser:
    build:
      context: .
      dockerfile: ./ParserSql/Dockerfile
    container_name: parser_container
    volumes:
      - ./ProcurementsDB:/ProcurementsDB/
    networks:
      supernetwork:
        ipv4_address: 171.20.0.5

  bot:
    build:
      context: .
      dockerfile: ./BotSqlJava/Dockerfile
    container_name: bot_container
    volumes:
      - ./ProcurementsDB:/ProcurementsDB
    networks:
      supernetwork:
        ipv4_address: 171.20.0.6
    depends_on:
      - parser

  backspring:
    build:
      context: .
      dockerfile: ./BackSpringJava/Dockerfile
    container_name: backspring_container
    volumes:
      - ./ProcurementsDB:/ProcurementsDB
    ports:
      - 8080:8080
    networks:
      supernetwork:
        ipv4_address: 171.20.0.7
    depends_on:
      - parser


networks:
  supernetwork:
    ipam:
      config:
        - subnet: 171.20.0.0/24

volumes:
  parser:
  bot:
  backspring:
